name: Discord Post
author: zio3
description: >
  WebHookCustom
inputs:
  webhookUrl:
    description: Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    required: true
  message:
    description: 通知っセージ
    required: false
  embedUrl:
    description: リンクURL
    required: false
  embedTitle:
    description: リンクタイトル
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: orange
  icon: alert-triangle